version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: .devops/build/Dockerfile
    container_name: django-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  migration:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    container_name: django-migration
    command: python manage.py migrate --noinput
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: django-db
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: DjangoDB
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: